name: Hammer
main: georgianYT\Hammer\Main
api: 5.0.0
version: 1.0
website: https://github.com/georgianYT/Hammer-PMMP/
author: georgianYT

permissions:
  hammer.give:
    description: Allows players to use the hammer command
    default: op
