name: Hammer
main: georgianYT\Hammer\Main
api: 4.0.0
version: 1.0
website: https://github.com/georgianYT/Hammer-PMMP/
author: georgianYT

commands:
 hammer:
  description: "Give you a Hammer !"
  permission: hammer.give
 
